### ISSUE TITLE
There should be way to get the SecretKey's bytes

### ISSUE THREAD

**Issue by adityapk00** [rust-bitcoin/rust-secp256k1#121]
Right now, the `key::SecretKey` doesn't have a way to get the serialized bytes, like the `key::PublicKey` does via `PublicKey::serialize()`.

The only way to get them seems to be to go through json via serde:
```
let sk_bytes = &hex::decode(&serde_json::to_string(&sk).unwrap()[1..65]).unwrap();
```
which seems a bit round-about. Can we send a PR that just returns the bytes from the `SecretKey`?

**Comment by elichai** [comment]
`SecretKey` implements https://doc.rust-lang.org/std/ops/trait.Index.html
so you can just do `let priv: &[u8] = &sk[..];`. so you can then copy it into whatever data structure you need.

**Comment by adityapk00** [comment]
Oh, I somehow missed that. That works for me, thanks so much.
