### ISSUE TITLE
docs.rs failed to build secp256k1-0.13.0

### ISSUE THREAD

**Issue by devashishdxt** [rust-bitcoin/rust-secp256k1#126]
Documentation for latest release is not available on [docs.rs](https://docs.rs/crate/secp256k1/0.13.0).

**Comment by jonasnick** [comment]
This should've been fixed in this repo after merging https://github.com/rust-bitcoin/rust-secp256k1/pull/113/files. But I presume we need another release to fix this on docs.rs? @apoelstra

**Comment by apoelstra** [comment]
Yes, we need another release. Current codebase has breaking changes relative to 0.13.0 and I'd rather not do a backport just for docfixes.

Was planning to release 0.14.0 after fixing https://github.com/rust-bitcoin/rust-secp256k1/issues/118 but I guess there's no reason to block release on that. Will make one now.

**Comment by apoelstra** [comment]
Fixed in 0.14 https://docs.rs/secp256k1/0.14.0/secp256k1/ Thanks for the report!
