### ISSUE TITLE
Need a way to override `ECMULT_WINDOW_SIZE` externally

### ISSUE THREAD

**Issue by laanwj** [rust-bitcoin/rust-secp256k1#139]
Unfortunately I don't think it's possible to have integer-valued features in rust. But one possibility would be to have a feature for low-memory systems that reduces it to its minimum size, 3. Or the other way around, a default-enabled feature without which it will be 3, with it will be 15.

**Comment by elichai** [comment]
What do you think about using an environment variable to override the default 15? (that way low memory devices will set the environment variable when compiling)

**Comment by laanwj** [comment]
I'm not super happy about having to set environment variables during build, as they need to be set outside `Cargo.toml`, it's easy to forget them when calling cargo.

**Comment by apoelstra** [comment]
I think just adding a feature flag that'd turn 15 into 3 would be good.

**Comment by laanwj** [comment]
Thanks, will do!
