### ISSUE TITLE
Passing pointers to ZST to FFI

### ISSUE THREAD

**Issue by elichai** [rust-bitcoin/rust-secp256k1#142]
We have a bunch of functions that accept slices, these slices could be Zero Sized types if they're empty.
getting a pointer to ZST is implementation defined and could be NULL which might violates the ffi contract for non null values.
We should either explicitly check that the slices aren't empty or have our own pointer trait that always return a valid pointer

https://doc.rust-lang.org/nomicon/exotic-sizes.html#zero-sized-types-zsts

Example of having "our own `as_ptr`" https://github.com/enigmampc/enigma-core/blob/develop/enigma-types/src/traits.rs

I personally lean towards the first option of explicitly checking, the only problem with that is that we might forget. then it will hopefully call `secp256k1_callback_call` in the good case, and in a bad case create a UB

**Comment by apoelstra** [comment]
If we get UB that is a bug upstream. No such bugs should exist.

**Comment by elichai** [comment]
Well upstream docs do specify `Cannot be NULL` sometimes, I agree it should be checked there and I'm pretty sure it is checked everywhere, but the docs don't explicitly say that.

**Comment by apoelstra** [comment]
Every single `cannot be NULL` should be accompanied by an `ARG_CHECK` asserting that the argument is non-NULL. I'm not aware of any exceptions.

**Comment by elichai** [comment]
Solved by #151
