### ISSUE TITLE
Cannot use `std` without `rand` dependency

### ISSUE THREAD

**Issue by str4d** [rust-bitcoin/rust-secp256k1#150]
#136 added `rand/std` to the `std` feature. This change forces `rand` to be in the dependency tree when `std` is enabled, even if the `rand` feature is disabled. This makes it impossible to use `secp256k1` with `std` but without `rand` in the dependency tree.

**Comment by elichai** [comment]
Hmm that's not good.

I'm not sure what solutions rust offer. we might need to default rand to include std and if you want rand you must get std.
*Or* have a separate `rand-std` feature :/

**Comment by apoelstra** [comment]
Frustrating. https://github.com/rust-lang/cargo/issues/3494

I think a separate `rand-std` feature is the best option.

**Comment by elichai** [comment]
Can we close? https://github.com/rust-bitcoin/rust-secp256k1/pull/158
