### ISSUE TITLE
:bug: "generate_keypair is not found" in version 0.15.4

### ISSUE THREAD

**Issue by qiangshou007** [rust-bitcoin/rust-secp256k1#157]
mac
`rustc 1.39.0-nightly (2b8116dce 2019-09-08)`

change dependencies sepc256k1 version to 0.15.3, build Ok
`secp256k1 = "=0.15.3"`

**Comment by apoelstra** [comment]
Oops, https://github.com/rust-bitcoin/rust-secp256k1/pull/153 was part of 0.15.4 but it shouldn't have been included in a minor version release.

**Comment by apoelstra** [comment]
FYI for now using the `rand-std` feature rather than `rand` will fix it.
