### ISSUE TITLE
visibility for types, EcdhHashFn signature

### ISSUE THREAD

**Issue by shmishleniy** [rust-bitcoin/rust-secp256k1#160]
Hi,

1. ffi mod is under pub visibility but types mod is not, so actually I have no access to c_void in case if I would like to work with ffi module.
2. EcdhHashFn return type is void, but should be c_int

**Comment by elichai** [comment]
How do we feel about exposing the types module?

**Comment by real-or-random** [comment]
To be honest, I'm not sure if I'm competent enough to answer. Would there any drawbacks?

**Comment by elichai** [comment]
yes.
1. more public API to maintain.
2. Some of our types are *wrong* in some scenarios. but it's fine for us because we only use pointers there (ie `c_char`)

**Comment by apoelstra** [comment]
I think we should expose it so that people can use the FFI. It's unfortunate if things are wrong but it's understood that the ffi module has sharp edges and weirdness.

**Comment by elichai** [comment]
cool. maybe we can publicly re-export it through the `ffi` module (ie `ffi::types`). as long as people understand that they shouldn't use the FFI code without good understanding of what they're doing then it should be fine :)

**Comment by real-or-random** [comment]
> It's unfortunate if things are wrong but it's understood that the ffi module has sharp edges and weirdness.

I think that's a good summary.

**Comment by tcharding** [comment]
Neither of the issues described now exist, this can be closed.
