### ISSUE TITLE
How to get signature from r and s correctly

### ISSUE THREAD

**Issue by kigawas** [rust-bitcoin/rust-secp256k1#163]
I'm using `from_compact`, but sometimes it failed.

A failed example:
```
msg: 86192454590171687215412195207796227608163400619529459171495931324814217311680
r: 978b81444f5781f50a4e7afb093cec827d9815a05bce2acf056c442b7b609aeb
s: d5016270e4c9b91c9f00d299672138c432cffa2f83b92af358bd6d6f8bba3efb
pk: c6966890c87609c70f7390a3985f9f83809a270c17c4e6bb455db351e7d185023a13a2df06abf31ee94a47df9d0b38463bb235a25e1ea75aef3e1af726c8bf55
```

**Comment by jonasnick** [comment]
More details and a minimal example would be helpful. How did you generate the public key? Looks like the Y coordinate is wrong.
```
sage: F = FiniteField (0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F)
sage: x = F( 0xc6966890c87609c70f7390a3985f9f83809a270c17c4e6bb455db351e7d18502)
sage: hex(int(sqrt((x^3 + 7))))
'0x2563f47a098e229f8facc04ddd14cc5c2274cc76236844fe8727f95d74eb4014L'
```

**Comment by kigawas** [comment]
Thanks, I got them from another library using this library

I'll investigate more on this

**Comment by tcharding** [comment]
Hi @kigawas, is this issue live still?

**Comment by kigawas** [comment]
> Hi @kigawas, is this issue live still?

I'm not sure since already switched to [the pure Rust implementation](https://github.com/paritytech/libsecp256k1)

**Comment by tcharding** [comment]
Cool, thanks. Lets close this then.
