### ISSUE TITLE
FR: Have a method to construct a Secp256k1 context from a raw context pointer

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-secp256k1#178]
So when doing FFI's with C, you might want to pass your C-allocated secp context into your Rust FFI. Currently, I don't see a way to do that.

I tried implementing such a thing, but all the subtleties of memory freeing and the whole capability thing overwhelm me a bit. I feel like I'm not the right person to write this.

So a feature request for someone with more experience with the lower level workings of this library :)

I tried something like this, but I'm running into problems and like this it will also deallocate the buffer on `Drop`, which should be prevented: (diff on top of https://github.com/rust-bitcoin/rust-secp256k1/pull/169):
```diff
diff --git a/src/context.rs b/src/context.rs
index 490bb58..11dc557 100644
--- a/src/context.rs
+++ b/src/context.rs
@@ -96,6 +96,19 @@ mod std_only {
                 buf: ptr,
             }
         }
+
+        /// Create a context from a raw context.
+        ///
+        /// Please be extremely careful using this method. Especially ensure
+        /// that the capabilities assigned to this context match the
+        /// capabilities used when the context pointer was created.
+        pub unsafe fn from_raw(raw_ctx: *mut ffi::Context) -> Secp256k1<C> {
+            Secp256k1 {
+                ctx: raw_ctx,
+                phantom: PhantomData,
+                buf: Box::into_raw(Box::from_raw(raw_ctx as *mut [u8])),
+            }
+        }
     }
 
     impl Secp256k1<All> {
```

**Comment by elichai** [comment]
Is that really a valid good usecase we want to support?
If so I'd use the preallocated structs.
do we leave to the user to define the capabilities himself(using the genric)?
or can we at least check that it's valid? (i.e. is there a way in upstream to check the flags of an existing context?)

**Comment by apoelstra** [comment]
The use case is interop with C code that already has a secp context available, and which does not/cannot interact with the Rust code to produce the context. I think this is reasonable.

**Comment by elichai** [comment]
#179 is merged. Can you close? (don't have permissions here)
