### ISSUE TITLE
Expose scalar inversion method/function

### ISSUE THREAD

**Issue by jimpo** [rust-bitcoin/rust-secp256k1#181]
I don't see any way using this project to access the `secp256k1_scalar_inverse` and `secp256k1_scalar_inverse_var` functions. As the README says "exposes type-safe Rust bindings for all libsecp256k1 functions", I expected this to be possible. Is that something you consider safe to add?

It seems like all scalar operations are only exposed `SecretKey` using the `secp256k1_ec_privkey_*` functions. Are they deliberately hidden?

**Comment by elichai** [comment]
I don't see these methods in upstream :) 
https://github.com/bitcoin-core/secp256k1/blob/master/include/secp256k1.h

**Comment by jimpo** [comment]
@elichai Ah, I confused the public API with the internal APIs. Nevermind then, I'll think about alternatives.

**Comment by elichai** [comment]
Anyway that sounds more like a conversation for upstream.
Good Luck.
