### ISSUE TITLE
Why is the cc version limited?

### ISSUE THREAD

**Issue by laanwj** [rust-bitcoin/rust-secp256k1#202]
The `cargo.toml` for `secp256k1-sys` has the following:
```
[build-dependencies]
cc = ">= 1.0.28, <= 1.0.41"
```
I need a newer version of `cc` due to recent risc-v toolchain changes, so I wonder. It looks like this specification was there from the beginning, I could not find anything in the commit messages.

**Comment by elichai** [comment]
It was because cc broken MSRV.
https://github.com/rust-bitcoin/rust-secp256k1/pull/156

Cc https://github.com/rust-bitcoin/rust-bitcoin/issues/338

**Comment by laanwj** [comment]
I can't use the MSRV for my target hardware anyway.

Do you perhaps know if there is any way to override this in an application?

**Comment by elichai** [comment]
> I can't use the MSRV for my target hardware anyway.
> 
> Do you perhaps know if there is any way to override this in an application?

I just tried using `patch` and `replace` and I do not think this is possible :/
it seems like you must either fork `rust-secp256k1` or `cc` (and replace the version in cc's Cargo.toml to `1.0.41` and then you can use either patch or replace to do this)

**Comment by laanwj** [comment]
Right—I currently have a forked `cc-rc`:  https://github.com/laanwj/cc-rs/tree/2019_08_riscv_medany (this is 1.0.14 with the patch on top)
I explicitly override to use this in the workspace: https://github.com/laanwj/k210-sdk-stuff/blob/master/rust/Cargo.toml#L23 

This works, but I was hoping to move away from that.

**Comment by ArtemGr** [comment]
FYI,
```
C:\spool\synced\projects\mm-pubsub-db>cargo update
    Updating crates.io index
    Updating git repository `https://gitlab.com/artemciy/sqlite-mm`
error: failed to select a version for `cc`.
    ... required by package `zstd-sys v1.4.15+zstd.1.4.4`
    ... which is depended on by `zstd-safe v2.0.3+zstd.1.4.4`
    ... which is depended on by `mm-pubsub-db v0.1.0 (C:\spool\synced\projects\mm-pubsub-db)`
versions that meet the requirements `^1.0.45` are: 1.0.52, 1.0.51, 1.0.50, 1.0.49, 1.0.48, 1.0.47, 1.0.46, 1.0.45

all possible versions conflict with previously selected packages.

  previously selected package `cc v1.0.28`
    ... which is depended on by `secp256k1-sys v0.1.0`
    ... which is depended on by `secp256k1 v0.17.0`
    ... which is depended on by `mm-pubsub-db v0.1.0 (C:\spool\synced\projects\mm-pubsub-db)`

failed to select a version for `cc` which could resolve this conflict
```

**Comment by Darkspirit** [comment]
Your crate can't be used with `ring` anymore: https://github.com/briansmith/ring/issues/984
Please remove the restriction.
