### ISSUE TITLE
Pubkey negation function is missed

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-secp256k1#221]
The pubkey negation function `secp256k1_ec_pubkey_negate` from the original secp256k1 library is missed. It can be useful in situations like implementation of ElGamal encryption.

**Comment by real-or-random** [comment]
https://github.com/rust-bitcoin/rust-secp256k1/pull/220

**Comment by dr-orlovsky** [comment]
Sorry, missed that. Already did a PR #222, but closing it in favor of #220

**Comment by real-or-random** [comment]
Can I ask if you really need this for ElGamal encryption? Use cases are always interesting for us. The idea of (rust-)secp256k1 is to be a high-level library for a few well-defined primitives, e.g., signatures and ECDH key exchange. It's not intended to be a low-level library for implementing other primitives such as ElGamal. Of course, that's sometimes possible by (ab)using the internal function, and I'm not arguing against this. But then I feel the more we provide pseudo high-level functions such as key arithmetic, the more they will be used against the purpose of the library. Maybe there's a need for a low-level library, too?

**Comment by dr-orlovsky** [comment]
ElGamal use case was discussed yesterday in #bitcoin-wizards: <http://gnusha.org/bitcoin-wizards/2020-06-11.log> (look for `ElGamal` string)

I did my own implementation today within our LNP/BP library, providing primitives for the layers & apps on top of Bitcoin and LN: <https://github.com/LNP-BP/rust-lnpbp/pull/46>

I am using it in https://github.com/pandoracore/keyring and plan to use it with Storm – a layer for storage smart contracts with Bitcoin: <https://github.com/storm-org/storm-spec>

**Comment by apoelstra** [comment]
Closed by #220
