### ISSUE TITLE
Enable GLV optimization?

### ISSUE THREAD

**Issue by oleiba** [rust-bitcoin/rust-secp256k1#241]
Now that [U.S. Patent No. 7,110,538](https://patents.google.com/patent/US7110538B2/en) has expired, the endomorphism optimization for point multiplication can be enabled by default. Also, it is already implemented in libsecp256k1 but was just turned off by default.
Is it already supported with this crate, or expected to be supported with a future release?

**Comment by real-or-random** [comment]
upstream will just remove the non-endo code, so we'll get this automatically with the first update afterwards: https://github.com/bitcoin-core/secp256k1/pull/826#issuecomment-700272712

**Comment by oleiba** [comment]
Great. 
So just to make sure I got it right: there is no need for another release because the `git clone https://github.com/bitcoin-core/secp256k1.git` takes the HEAD by default, correct?
For a library using this crate, it would simply require doing a `cargo build`?

**Comment by real-or-random** [comment]
No, we need a release. We have a copy of secp256k1 in our repo. When we update the copy, we will bump secp256k1-sys, see https://github.com/rust-bitcoin/rust-secp256k1/pull/229 for a past example.  I think we want to do this as soon as https://github.com/bitcoin-core/secp256k1/pull/826 is merged.

**Comment by oleiba** [comment]
OK, makes sense. I will follow for the upcoming release.
BTW, I think this would also allow deleting the `endomorphism` feature, as it would always be turned on.

**Comment by elichai** [comment]
@oleiba for now feel free to enable the feature for your crates, 
as @real-or-random we'll probably wait for  bitcoin-core/secp256k1#826 to be merged and maybe even safeGCD before we will update upstream here and remove the feature

**Comment by apoelstra** [comment]
I think we should leave this open as a tracking issue for "GLV by default".

It's also worth considering us turning on the feature by default, which we can do in a minor release.

**Comment by elichai** [comment]
I think this is done since https://github.com/rust-bitcoin/rust-secp256k1/commit/e687622a81c668e75308a357a8037ed4b84ad336

This is done from secp256k1 version 0.20.0 and up.
