### ISSUE TITLE
implement Deref trait for SecretKey

### ISSUE THREAD

**Issue by toxeus** [rust-bitcoin/rust-secp256k1#245]
The `Deref` trait is implemented for `SharedSecret` and `SerializedSignature`. I was wondering if you have considered implementing that trait also for `PublicKey` and `SecretKey` already?

**Comment by apoelstra** [comment]
What would they `Deref` to? The internal representation is opaque and subject to change.

**Comment by toxeus** [comment]
I thought they would `Deref` to `&[u8]`.

**Comment by toxeus** [comment]
`SecretKey` already allows access to the internal representation https://docs.rs/secp256k1/0.19.0/secp256k1/key/struct.SecretKey.html#method.as_ref. I think implementing `Deref` would be  useful and consistent with the types mentioned above.

**Comment by elichai** [comment]
A. The internal representation of PublicKey is Implementation Defined, so to impl `Deref` you'd have to serialize it each time.
B. I actually think we should decrease things magic implementations like Deref, not increase, because they give a bunch of functions that don't really makes sense for `SecretKey` (on the other hand I do love abusing it sometimes because you magically get a bunch of functions for free)

**Comment by toxeus** [comment]
I agree with A. Let me adjust the issue title to reflect that. 

About B: `Deref` is widely used in Rust and part of the language. Personally, I like it. I can understand that some perceive it as "magic" but this can be argued about many language features really and if you strictly go down that path you end up with golang ;)

Still, the inconsistency between `SharedSecret` and `SerializedSignature` on one hand and `SecretKey` on the other still exists. I'd like to understand when "magic" is warranted and when not.

**Comment by elichai** [comment]
> About B: `Deref` is widely used in Rust and part of the language. Personally, I like it. I can understand that some perceive it as "magic" but this can be argued about many language features really and if you strictly go down that path you end up with golang 


Don't get me started on "magic" in golang :) (comments are magic, the amount of return values from maps/channels is magically chosen by how many lvalues you have, cgo is 100% pure magic, which pointers the GC tracks is magic, should I continue? :) )

**Comment by apoelstra** [comment]
I think `Deref` in Rust is uniquely magical :)

**Comment by apoelstra** [comment]
In any case -- I think we should probably go in the direction of removing access to the internal representation (or providing a `convert_to_ffi` method in its stead). The internal representation is almost certainly not what the user wants unless they are doing magic FFI stuff (and then I would argue that they should never have started using the non-FFI types to begin with..). See #248 for example of where people got burned by the internal representation not resembling an actual public key.
