### ISSUE TITLE
Question: Is usage of static context via lazy_static for WASM insecure?

### ISSUE THREAD

**Issue by junderw** [rust-bitcoin/rust-secp256k1#265]
Example:

```rust
#[macro_use]
extern crate lazy_static;
lazy_static! {
    static ref SECP: Secp256k1<secp256k1::All> = Secp256k1::new();
}
```

Then use `SECP` in any function (exposed to JS via wasm_bindgen) that needs it.
Pretty much using the same context for everything, including operations that use private key material.

Perhaps I should offer a method to reset/randomize the context and tell the consumer to use it appropriately for their app?

**Comment by apoelstra** [comment]
You can use the same context for everything. Re-randomizing gives some defense in depth but it's not necessary.

Having said that I would not be handling secret key material in Javascript under any circumstances.

**Comment by junderw** [comment]
Sounds good.

> I would not be handling secret key material in Javascript under any circumstances.

That's why we're experimenting with rust + WASM.

**Comment by junderw** [comment]
I'm almost tempted to re-write BitcoinJS entirely in rust and expose it through WASM...

I just don't really have the time.

**Comment by thomaseizinger** [comment]
@junderw Note that rust-secp256k1 already exposes such a context of you enable the "global-context" feature!
