### ISSUE TITLE
Performance regression on wasm

### ISSUE THREAD

**Issue by real-or-random** [rust-bitcoin/rust-secp256k1#278]
@gregdhill wrote this upstream (https://github.com/bitcoin-core/secp256k1/issues/892)

> Not sure if this is an issue with the [rust-bindings](https://github.com/rust-bitcoin/rust-secp256k1), but the performance of [bitcoin-core/secp256k1](https://github.com/bitcoin-core/secp256k1) is distinctly slower than other Rust based libraries when compiled to Wasm. See the example benchmarks [here](https://github.com/gregdhill/bench-secp256k1-wasm).

Since this is a regression, it should be easy to git bisect this.

Possibly related: https://twitter.com/alexeiZamyatin/status/1355605818218053637

**Comment by elichai** [comment]
Answered in the original issue: https://github.com/bitcoin-core/secp256k1/issues/892#issuecomment-771704200

**Comment by real-or-random** [comment]
Solved in https://github.com/bitcoin-core/secp256k1/issues/892#issuecomment-771704200
