### ISSUE TITLE
ECDSA adaptor signature implementation

### ISSUE THREAD

**Issue by GeneFerneau** [rust-bitcoin/rust-secp256k1#292]
I've recently implemented the [ECDSA adaptor signature scheme](https://github.com/geneferneau/adaptor) from [Generalized Bitcoin-Compatible Channels](https://eprint.iacr.org/2020/476.pdf).

The library solely depends on `rust-secp256k1`, and I made some changes to expose some necessary functions. In your contributing guide, it suggests making all crypto contributions upstream to the C `libsecp256k1` library. Would the changes I've made to `rust-secp256k1` ([geneferneau/rust-secp256k1@2e6e833](https://github.com/rust-bitcoin/rust-secp256k1/compare/master...GeneFerneau:adaptor)) be welcome as a PR here, or should I upstream by re-implementing ECDSA adaptor signatures in `libsecp256k1`?

My next steps are to implement Schnorr adaptor signatures, so same questions there.

Thanks for any feedback.

**Comment by real-or-random** [comment]
I assume you're not aware of https://github.com/ElementsProject/secp256k1-zkp/pull/117 ?

**Comment by GeneFerneau** [comment]
> I  assume you're not aware of ElementsProject/secp256k1-zkp#117 ?

No, definitely was not :facepalm:

I did a search for ECDSA adaptor signature implementations before I got started, but didn't find that impl.

At least now I thoroughly understand how ECDSA adaptor signatures work...

Thanks for the link.

**Comment by real-or-random** [comment]
> Their impl doesn't appear to contain a proof for `Y = y*g` specified in the work by Aumayr et al. In that work, they specify it is required for the scheme to be secure under the Universal Composability framework. What's a good way to bring that to their attention / start a discussion?

That's an interesting point. 

Just reply in the PR there. It was merged just earlier this week.

**Comment by GeneFerneau** [comment]
> Just reply in the PR there. It was merged just earlier this week.

Ok, will do.

**Comment by heygauri** [comment]
Hello, I was searching for the implementation of Schnorr adaptor signatures and came across this conversation. Can I ask where I can find it? I checked https://github.com/BlockstreamResearch but didn't find any clues. I would be glad if anyone could help me with this. I find this conversation relevant, so I'm posting here.

**Comment by real-or-random** [comment]
> Schnorr adaptor signatures

See this issue: https://github.com/BlockstreamResearch/secp256k1-zkp/issues/191 Spoiler: There is no implementation.
