### ISSUE TITLE
KeyPair serialization

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-secp256k1#298]
May be I am missing something, but I see no way of serializing `KeyPair` in binary form: unlike `SecretKey` it keeps FFI-based representation of the data (and not the actual secret key value), so they can't be accessed via `Index`ing, but on the other hand it does not implement `serialize` function as other types using FFI inner representation (like `PublicKey`s).

At the same time there is a `KeyPair::from_slice` method, constructing it from a serialized version, which one can't obtain from the rust library.

**Comment by elichai** [comment]
That's because our upstream version is from before https://github.com/bitcoin-core/secp256k1/pull/845, we can now update it and add a `serialize_seckey()` function or something like that to `KeyPair`

**Comment by dr-orlovsky** [comment]
Shell I work on a PR?
