### ISSUE TITLE
Touch recovery module from no_std_test

### ISSUE THREAD

**Issue by jules23** [rust-bitcoin/rust-secp256k1#301]
Would it be possible to touch some of the functions in the recovery module in the no_std_test script?

I've confirmed myself that a function like `sign_recoverable` can run in a `no_std` environment, but that function isn't tested in that script.

I also initially took the no_std_test to be a list of all the functionality available in `no_std`, so clarifying that this is not an exhaustive list could be helpful as well.

Thank you!

**Comment by real-or-random** [comment]
Yep, I guess we should add them.

This sounds like a "good first issue". Would you willing be to contribute a PR?

**Comment by jules23** [comment]
Yes!
