### ISSUE TITLE
Is there a way to work with 128-bit private keys?

### ISSUE THREAD

**Issue by ilmoi** [rust-bitcoin/rust-secp256k1#321]
Currently, on running the below function:
```
let main_prvk = secp256k1::SecretKey::from_slice(entropy).unwrap();
```
with this entropy:
```
[251, 118, 109, 233, 13, 244, 33, 251, 157, 96, 197, 225, 97, 233, 161, 18]
```
I'm getting this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidSecretKey', src/eth/external.rs:25:64
```

After a bit of digging I discovered that the `from_slice()` function that I'm calling requires a private key of size `SECRET_KEY_SIZE`, which is set to 32 bytes or 256 bits.

Is there a way to get around that without directly modifying the `constants` file? I'm not familiar with the library code and don't have a strong cryptography background so I'm vary about changing the constant directly. Is there a recommended approach? Or does this library basically only support 24-word mnemonics (256 bit entropy)?

**Comment by TheBlueMatt** [comment]
This library expects a secp256k1 secret key, which is always 32 bytes. In general you should be applying some kind of hashing or stretching to your entropy and not using it directly as a secret key. You probably shouldn't use less than 256 bits of entropy for private key material ever, but if you really need to, hash it first.

**Comment by real-or-random** [comment]
> Or does this library basically only support 24-word mnemonics (256 bit entropy)?


This library does not support 24-word mnemonics at all. If you have mnemonic, you first need to derive a secret key from it. This secret key is then supported by the library.

**Comment by ilmoi** [comment]
@TheBlueMatt interesting, so I'm a little confused here. Currently my wallet implementation follows bip-39. At least I think it does, as comparing to [this website](https://iancoleman.io/bip39/), I arrive at the same derived addresses / private keys / public keys as they do, when starting from the same mnemonic. 

But then eg a mnemonic of 12 words produces 128 bits of entropy, which you say should be hashed first? But if I hash it, wouldn't that result in a different set of addresses / private keys / public keys in the end, breaking the bip-39 standard?

Perhaps there's some major misunderstanding on my part somewhere here. It could also be possible that `secp256k1` is the wrong library for my use-case (building an ethereum bip39 wallet)? I decided to go with it based on [this chapter of Mastering Ethereum](https://github.com/ethereumbook/ethereumbook/blob/develop/04keys-addresses.asciidoc).

[Here's](https://github.com/ilmoi/eth-rust-wallet/blob/master/src/main.rs) a minimally runnable version of my wallet code.

Would appreciate any guidance, I'm totally new to this!

**Comment by real-or-random** [comment]
When we say "hashing", we mean the conversion from mnemonic to seed as described here  https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#from-mnemonic-to-seed (which is part of BIP39) . If you check the tool you posted, the resulting BIP39 seed will be of the same length, no matter how long the mnemonic is.

> @TheBlueMatt interesting, so I'm a little confused here. Currently my wallet implementation follows bip-39. At least I think it does, as comparing to [this website](https://iancoleman.io/bip39/), I arrive at the same derived addresses / private keys / public keys as they do, when starting from the same mnemonic.

Well than everythigng seems good! Note that other places like stackexchange may be more suitable for questions like this.

**Comment by real-or-random** [comment]
> How do I go from 64 bytes to 32 bytes?

This is where BIP32 is used:
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

**Comment by ilmoi** [comment]
I see, you have to take the left 32 bytes as the private key and leave the right 32 bytes for the chain code. It's clear now.

Thanks for all the help. Really appreciate it.
