### ISSUE TITLE
Sign-to-contract support

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-secp256k1#338]
Currently it is impossible to tweak R value with a sign-to-contract scheme neither in ECDSA nor BIP-340 signature API. I propose to introduce new functions `Secp256k1::sign_to_contract` and `Secp256k1::schnorr_sign_to_contract` taking additional args of 32-byte tweak value (which must be within group order). The only question can we do it with the current C API or we need to update secp256k1 first.

**Comment by dr-orlovsky** [comment]
From what I see this should go to rust-secp256k1-zkp. secp256k1-zkp does already have S2C for ECDSA, but not for BIP-340, so it has to be implemented first

**Comment by apoelstra** [comment]
Agreed, rust-secp-zkp is the place to go for stuff like this.
