### ISSUE TITLE
Two public symbols with the same purpose

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#350]
The crate contains:

```rust
#[macro_use]
pub extern crate secp256k1_sys;
pub use secp256k1_sys as ffi;
```

These two symbols do the same thing just have a different name. Would it make sense to un-publish one of them to decrease doc clutter? Which is better?

**Comment by apoelstra** [comment]
I think we should keep the `ffi` one and drop the `-sys` one.

But there is an argument for keeping both ... we could imagine one day having a config flag to swap out `ffi` for a different crate (e.g. secp256k1-zkp-sys) while some users may want to refer specifically to one or the other. I don't really agree with this argument, but it's there.

**Comment by Kixunil** [comment]
I also don't agree with that argument simply because Cargo features must be additive and I don't see any way to swap the crates without causing incompatibilities.

**Comment by tcharding** [comment]
This was resolved recently, issue can be closed.
