### ISSUE TITLE
Use Once from std when available

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#352]
The current code in `secp256k1_context_preallocated_create` uses hand-rolled busy loop even when `Once` is available potentially wasting CPU. Abstracting them away and conditionally using `Once` from `std` would avoid the waste.

**Comment by elichai** [comment]
I think this is only for the fuzzing configuration?

**Comment by Kixunil** [comment]
Yeah, didn't notice, probably not worth the effort.

**Comment by TheBlueMatt** [comment]
Right, the point of the hand-rolled code there is precisely to avoid relying on std/thread sleeping in fuzzing. Honestly I forget what the configuration I was trying to match was when I wrote it, proabbly driller or similar.
