### ISSUE TITLE
rustsecp256k1_v0_4_1_context_* gated behind `std` but looks like it shoul've been `alloc`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#355]
These symbols have this configuration:

```rust
#[cfg(all(feature = "std", not(rust_secp_no_symbol_renaming)))]
```

However I don't see `std` strictly required in the bodies so it seems it should've been `alloc`. I tested it and have some WIP working code.
The `alloc` feature is not currently present but it can be added in backwards-compatible way so it shouldn't be an issue.

**Comment by tcharding** [comment]
This has been done, issue can be closed.
