### ISSUE TITLE
Should secrets imlpement Copy

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-secp256k1#363]
Currently `SecretKey` implements `Copy` (by way of `impl_arrayy_newtype!`).

This is issue is to save devs searching for relevant discussion since recently it came up in a rust-bitcoin [PR](https://github.com/rust-bitcoin/rust-bitcoin/issues/708#issuecomment-998301806).

ref: secp256k1-sys/src/macros.rs
```
macro_rules! impl_array_newtype {
    ($thing:ident, $ty:ty, $len:expr) => {
        impl Copy for $thing {}
```

**Comment by apoelstra** [comment]
I"m going to put my vote in as "yes, keep `Copy`" because it's quite unergonomic to remove it, and the security benefit is questionable at best.

**Comment by tcharding** [comment]
This has been open for a month so everyone has had time to chime in. Implement `Copy` it is :)
