### ISSUE TITLE
Fix the mess around Parity

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-secp256k1#370]
Recently I opened up a hornets nest by changing the parity boolean into an opaque type (#344). This PR was also flawed, @sanket1729 came to the rescue in #360 and #361.

There has now been much talk and disagreement on this, listing links here in an attempt to collect all the comments (in no particular order):
- https://github.com/rust-bitcoin/rust-bitcoin/pull/728#discussion_r760995314
- https://github.com/rust-bitcoin/rust-bitcoin/pull/755#pullrequestreview-846177363
- https://github.com/rust-bitcoin/rust-bitcoin/pull/718#pullrequestreview-815438975

**Comment by apoelstra** [comment]
My proposed solution:

* Redefine `Parity` to be an enum `Even`/`Odd` rather than an opaque type (not a breaking change)
* Add `to_u8` and fallable `from_u8` methods (we can bikeshed on names, I don't care) (not a breaking change)
* Add an `xor` method between two `Parity`s/overload the `^` operator (not a breaking change)
* Deprecate the existing `i32` conversion methods
* Make sure we have all the necessary `#derive`s :) (I think this is done)

So I think we can clean this all up with another minor version.

**Comment by tcharding** [comment]
Just noting that the first step is where we got stuck last time, the naming of `Even`/`Odd` and not knowing how this maps to the integer value.

**Comment by dr-orlovsky** [comment]
Hm, isn't it quite obvious: odd should be a first odd integer value - and even should be a first even integer value, i.e. odd is 0 and even is 1.

0 is indeed even, since 0 % 2 == 0, and by definition even are the integers which divide by 2 without reminder.

**Comment by apoelstra** [comment]
I agree that the mapping between 0/1 and even/odd is natural .. I'm not sure how this maps to the 02/03 prefixes on full keys, but I should hope also in the natural way!

**Comment by elichai** [comment]
> 

Yeah, in libsecp `0` is also used for even and `1` for odd.
(and in compressed 0x02 is for even and 0x03 is for odd)

I'm still somewhat uncomfortable exposing to users that public keys can even be "Even" or "Odd", but maybe this ship has long sailed.

**Comment by tcharding** [comment]
TIL: Cannot deprecate implementation of `From`.
```
#[deprecated(since = "0.21.3", note = "Please use Parity::from_i32")]
impl From<i32> for Parity {
    fn from(parity: i32) -> Parity {
        Parity::from_i32(parity)
    }
}
```
Results in:
error: this `#[deprecated]` annotation has no effect
--> src/key.rs:928:1
|
928 | #[deprecated(since = "0.21.3", note = "Please use Parity::from_i32")]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the unnecessary deprecation attribute
|
= note: `#[deny(useless_deprecated)]` on by default
```
