### ISSUE TITLE
New release just to update docs.rs?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#394]
I wonder if it'd make sense to make a new release just to update docs.rs. I *guess* @Shatnerz might got confused over at bitcoin because docs.rs doesn't show `ThirtyTwoByteHash` implementors (is that true?)

Don't want to push you just because *I* screwed up something, it's only an idea.

**Comment by apoelstra** [comment]
Is #390 basically this?

**Comment by Kixunil** [comment]
Oh, yes, sorry for not noticing.
