### ISSUE TITLE
SharedSecret should have a "deserialize from bytes" method and serde impls

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#416]
See discussion in #402 -- it looks like we accidentally removed this functionality when un-genericizing the struct.

**Comment by tcharding** [comment]
For my sanity I went back looking for the serde impls and I didn't find them either in the un-genericizing work or in the genercizing work either. This begs the question, is anyone even using this `SharedSecret`?

**Comment by apoelstra** [comment]
@tcharding I'm sure it has users, but by its nature it is an ephemeral thing which is not explicitly communicated, and I'm doubtful that anybody is trying to store/load it.
