### ISSUE TITLE
Add support for noncedata in secp.sign_ecdsa and secp.sign_ecdsa_recoverable

### ISSUE THREAD

**Issue by junderw** [rust-bitcoin/rust-secp256k1#424]
I would like to add (and am willing to make a PR) these two new methods.

I propose the names be `sign_ecdsa_with_noncedata` and `sign_ecdsa_recoverable_with_noncedata` and their function signatures add an extra argument at the end of type `[u8; 32]` and called `noncedata`.

Questions:

1. I would be willing to do this PR, but I want to get an idea of the willingness to add this to the API. Any objections?
2. Should I also add a new wrapper struct (similar to the other structs such as `Message` etc.)?

**Comment by apoelstra** [comment]
1. Sure, we'll take the new methods.
2. No, no reason to wrap the data. It's raw, unstructured data.
