### ISSUE TITLE
Provide more utility methods for conversion between basic pubkey/secret key types

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-secp256k1#428]
Similar motivation for the first commit of #372 

> Add method KeyPair::public_key
Currently to get the `XOnlyPublicKey` from a `KeyPair` users must do
`XOnlyPublicKey::from_keypair(&kp)`. While this does the job we can make
the lib more ergonomic by providing a method directly on `KeyPair` that
calls through to `XOnlyPublicKey::from_keypair`.

I think we should have more conversion methods 
- KeyPair:
   - secret_key() -> SecretKey
   - x_only_pub_key() -> XOnlyPublicKey
   - pub_key() -> PublicKey See(https://github.com/rust-bitcoin/rust-secp256k1/pull/372/commits/389abddcc789da672071aa9ae452664aeecce9ec#r831616364)
   
- SecretKey:
  - keypair() -> KeyPair
  - x_only_pub_key() -> XOnlyPublicKey
  - pub_key() -> PublicKey

- XonlyPublicKey:
  - pub_key() -> PublicKey
 
- PublicKey:
  - x_only_pub_key() -> (XonlyPublicKey, Parity)
  
  
I would like to call these methods `pubkey` instead of `pub_key`, but I think because of https://github.com/rust-bitcoin/rust-secp256k1/pull/372#discussion_r831616364 it might be difficult.

**Comment by tcharding** [comment]
I like `pubkey` better too, don't know why I used `public_key`.

By far the most important reason for favouring `pubkey` is that my editor does not catch the annoyingly common typo 'pubic key`.

**Comment by sanket1729** [comment]
Sorry, I meant to highlight this comment, not the commit. https://github.com/rust-bitcoin/rust-secp256k1/pull/372#discussion_r831616364

**Comment by sanket1729** [comment]
If you don't mind quick breaking changes, my preference would be: 

1) public_key()
2) pubkey()
3) pub_key()

**Comment by apoelstra** [comment]
I agree with your ranking.

**Comment by tcharding** [comment]
I'll hack it up!

**Comment by tcharding** [comment]
We currently have `PublicKey::from_secret_key_global` do we want more of these `_global` functions for all the conversion functions that take a secp parameter?

**Comment by sanket1729** [comment]
> We currently have PublicKey::from_secret_key_global do we want more of these _global functions for all the conversion functions that take a secp parameter?

I have never used them downstream. But, I would not complain we have those. No strong opinions on this.

In the near future, we will have static contexts in upstream libsecp, so we can later update our APIs to remove the secp param altogether.

**Comment by tcharding** [comment]
> In the near future, we will have static contexts in upstream libsecp, so we can later update our APIs to remove the secp param altogether.

With that in mind I won't add `_global` versions then.
