### ISSUE TITLE
Document unsafe code

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-secp256k1#447]
We have a whole bunch of unsafe code and non of the safety preconditions are documented.

If https://github.com/rust-bitcoin/rust-secp256k1/pull/448 merges, remove the compiler attributes in main crate and also `secp256k1-sys` crate that allow the lint: `#![allow(clippy::missing_safety_doc)]`.

**Comment by Kixunil** [comment]
Doing `unsafe` code review while documenting would be interesting for me. Reminds me #359 is still open.
