### ISSUE TITLE
`KeyPair::sign_schnorr` moved value

### ISSUE THREAD

**Issue by Tibo-lg** [rust-bitcoin/rust-secp256k1#452]
Is it on purpose that `msg` is moved in this function? I would guess that it isn't since it's just then passed by reference to the next method but was wondering.
https://github.com/rust-bitcoin/rust-secp256k1/blame/master/src/key.rs#L1023

**Comment by tcharding** [comment]
> I think we're moving toward copying values throughout the library.

Just to check I'm up to speed and help @Tibo-lg too, we are using `Copy` if the arg is 32 bytes or less, right? (To include keys.)
