### ISSUE TITLE
`impl Default for SerializedSignature` doesn't seem to make sense

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#454]
It's all zeroes, thus invalid signature. It's used in the implementation which could use `MaybeUninit` to avoid zeroing or, if we're too paranoid for that, there could be an internal constant `ZEROED`. If there's anyone actually using zeroed signatures we could make it `pub`.

**Comment by apoelstra** [comment]
Oops! This dates back to https://github.com/rust-bitcoin/rust-secp256k1/pull/100 and was probbaly an oversight. It shouldn't exist.
