### ISSUE TITLE
impl_array_newtype in FFI should not autoderive std::Hash

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#463]
In our FFI module we implement the std::Hash trait by hashing the contents of the inner array ... but the contents of these arrays for FFI types is not guaranteed to be consistent between different copies of the library. We shoud instead be serializing the data and comparings serializations.

The same applies to Ord and Eq.

related #462

**Comment by tcharding** [comment]
The same concern applies to `Index`, does it not? We should not enable indexing into the inner array from the outer types (not the `ffi` types) if the contents of the inner array is not guaranteed.

(What is the proper easy terminology for the "outer" types, the ones in `rust-secp256k1` not `secp256k1-sys`?)

**Comment by apoelstra** [comment]
Fixed by #506 ?

**Comment by apoelstra** [comment]
Only if those types already have a different representation while fuzzing.

IOW if it works without thinking about fuzzing, that's the way to go.

**Comment by tcharding** [comment]
I'm not currently able to find all the discussion we had on this ord/cmp stuff. I've done #515 that fixes ord/cmp at the level of `secp256k1` but I'm not sure now what the behaviour should be in `secp256k1-sys` - should we be providing ord/cmp implementations that use the underlying bytes or not? Is the fix in #515 at the right layer or should it have been in `secp256k1-sys`? Should we be providing `cmp_fast_unstable` or some such thing?

**Comment by apoelstra** [comment]
I like the idea of providing `cmp_fast_unstable` and documenting that it may not be consistent between versions of the library, even minor ones. I don't think that's MSRV breaking, or rather, I think it's an acceptable MSRV break. This would just compare the underlying bytes.

As for "where is the correct layer to do this", I'm fine either way: we could add these impls in `secp256k1-sys` and then call into those from `secp256k1`, or just not have `Ord`/`Eq` at all on the secp-sys types and only implement them in `secp256k1`. I'll ACK whatever you've already implemented :P.
