### ISSUE TITLE
Tag 0.24.4 exists

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-secp256k1#478]
Little tagging error @apoelstra, we have a `secp256k1-0.24.4` tag.

**Comment by apoelstra** [comment]
Can you link to it? I don't see it anywhere and git is telling me it doesn't exist on the remote.

**Comment by sanket1729** [comment]
I don't see it too.

**Comment by tcharding** [comment]
Bizarre, I see it locally but not through github, I'll close and ignore it :) FTR its on the same commit as the `secp256k1-0.23.4` tag. 

This is the commit copied from my shell.
```
125211d (tag: secp256k1-0.24.4, tag: secp256k1-0.23.4) Merge rust-bitcoin/rust-secp256k1#474: Disable re-randomization under more conditions
```

**Comment by apoelstra** [comment]
Sorry, it did briefly exist but @sanket1729 flagged it in #477 and I fixed it quickly.
