### ISSUE TITLE
Error compiling secp256k1-sys with wasm32 target

### ISSUE THREAD

**Issue by josediegorobles** [rust-bitcoin/rust-secp256k1#479]
That's the error shows when i do an: cargo build --target wasm32-unknown-unknown

running: "ar" "cq" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/libsecp256k1.a" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/wasm/wasm.o" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/depend/secp256k1/contrib/lax_der_parsing.o" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/depend/secp256k1/src/precomputed_ecmult_gen.o" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/depend/secp256k1/src/precomputed_ecmult.o" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/depend/secp256k1/src/secp256k1.o"
  cargo:warning=ar: /home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/libsecp256k1.a: invalid operation
  exit status: 1

  --- stderr

  error occurred: Command "ar" "cq" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/libsecp256k1.a" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/wasm/wasm.o" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/depend/secp256k1/contrib/lax_der_parsing.o" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/depend/secp256k1/src/precomputed_ecmult_gen.o" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/depend/secp256k1/src/precomputed_ecmult.o" "/home/jdrobpar/Projects/rust-secp256k1/target/wasm32-unknown-unknown/debug/build/secp256k1-sys-b353fabb5f9c23da/out/depend/secp256k1/src/secp256k1.o" with args "ar" did not execute successfully (status code exit status: 1).

**Comment by tcharding** [comment]
The command you posted runs ok for me (excluding a million C compiler warnings). Perhaps its something to do with your environment. What machine are you building on? I'm on Ubuntu 20.04.

**Comment by josediegorobles** [comment]
Same Ubuntu version yeah.

**Comment by tcharding** [comment]
I've no clue off the top of my head, are you able to list a few of the other debugging things you've tried to see if something jumps out at me? Build another crate with wasm32 is the first thing that jumps to mind. Cheers

**Comment by tcharding** [comment]
Sorry mate, I have no clue. Perhaps someone else on the team will have an idea.

**Comment by lwshang** [comment]
I encountered the same problem on my mac. The solution was to use ar/cc via llvm.
```
brew install llvm
LLVM_PATH=$(brew --prefix llvm)
AR="${LLVM_PATH}/bin/llvm-ar" CC="${LLVM_PATH}/bin/clang" cargo --target wasm32-unknown-unknown --release
```
Probably this fix also applies on linux.

**Comment by josediegorobles** [comment]
It's working like this without problem,  thanks @lwshang
