### ISSUE TITLE
`cargo test --no-default-features --features=rand-std` fails

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#494]
It looks like the tests in #492 just aren't annotated properly, so my local tests fail. Not sure why I didn't notice this at the time I merged that PR.

`cargo build` succeeds (with some warnings about unreachable code) so I don't think this is a problem for any downstream crates.

**Comment by tcharding** [comment]
We can close this one, fixed by https://github.com/rust-bitcoin/rust-secp256k1/pull/520
