### ISSUE TITLE
impl_array_newtype

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-secp256k1#501]
Is the `impl_array_newtype` macro in `secp256k1-sys/src/macros.rs` correct for usage in `secp256k1` modules? It differs from the one in `rust-bitcoin/internals/macros.rs`? It would be nice to move `new` and `from_array_unchecked` into the macro but that would make it even less suitable for `secp256k1`. 

Should we depend on the `internals` crate once it is released?

**Comment by apoelstra** [comment]
I'd rather this crate not depend on `bitcoin-internals`, and instead continue to have its own set of independently implemented macros.

`bitcoin-internals` has no stability guarantee and lives in a different repo, and I worry that we'll make changes there without considering how they might affect rust-secp.

**Comment by tcharding** [comment]
Fair point, thanks.
