### ISSUE TITLE
Document **all** safety requirements or remove undocumented `unsafe` functions from public API

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#544]
Several `unsafe` functions have this in their Safety documentation:

> This list *is not* exhaustive, and any violation may lead to Undefined Behavior.

Which is essentially same as saying: "if you don't obey secret rules this is UB" and since the code can never guarantee obeying secret safety rules it's equivalent to `core::hint::unreachable_unchecked` but without improved performance.

In other words those functions are totally useless.

Thus I propose for each function to either document **all** the rules (and make really, really sure they are correct) or just remove it from API if the rules can not be guaranteed.

**Comment by tcharding** [comment]
We also need to be super careful in future reviewing patches to functions with safter docs that the docs don't go stale. I was a bit worried about this when I wrote docs that are based on line-by-line parts of the function, they are begging to go stale.

**Comment by apoelstra** [comment]
>In other words those functions are totally useless.

Well, in fairness, it's more like "they're useless unless you read all the source, including the C source, and you know all the UB rules for both languages and you're logically omniscient" ;).

But I agree, we absolutely should fix this.
