### ISSUE TITLE
Clean up `NonNull` usage

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#546]
Moving discussion from https://github.com/rust-bitcoin/rust-secp256k1/commit/082c3bdd1c5a3f661ce806445f0a7a5e8ce92277#r91588011

In #542 we introduced the `NonNull` field for our internal secp context pointer. As @Kixunil observed, we could actually clean up this code by replacing `NonNull::new_unchecked` with `NonNull::new().unwrap_or_else(|| /* our existing allocation failure-checking code */)`. But when trying to implement this I got a bit frustrated because it would require that we fish `NonNull<T>`s through the FFI, which currently expects and returns `*mut T`s.

According to [this SE post](https://stackoverflow.com/questions/49392712/is-it-valid-to-use-ptrnonnull-in-ffi) we can use `NonNull<T>` in FFI bindings that are expecting `*mut T`. (The reasoning is that `NonNull` is marked `#[refr(transparent)]`...and it's hard for me to think why they'd have this marker, other than to enable FFI bindings like this.)

This would be semver-breaking but I believe it would more accurately document the FFI API, if we were to replace all `*mut Context` pointers with `NonNull<Context>`. The C code currently does `VERIFY_CHECK(ctx != NULL)` for context objects and then assumes that its passed pointers are non-NULL. With our current compilation flags, `VERIFY_CHECK` is compiled to nothing at all, so basically right now if you pass NULL context pointers to our FFI you'll get UB.

One unfortunate thing is that this means that we wouldn't be able to implement `CPtr` for `secp256k1::Context`, which is our designated "expose types from `secp256k1-sys` which is not stable" semver escape hatch.

cc @Kixunil

**Comment by Kixunil** [comment]
> it's hard for me to think why they'd have this marker, other than to enable FFI bindings like this

The marker *is* intended for FFI, so if they meant something else they'd have to document that we must not rely on it.

> I believe it would more accurately document the FFI API

I agree, we should do it at some point.

>  wouldn't be able to implement `CPtr` for `secp256k1::Context`, which is our designated "expose types from `secp256k1-sys` which is not stable" semver escape hatch.

How's that "escape hatch" supposed to work? I never really understood the point of the trait.

**Comment by apoelstra** [comment]
> I agree, we should do it at some point.

So, if we did it now, prior to releasing 0.25.0 (which was conveniently delayed because we rely on a new secp-sys that we forgot to publish first), then we could avoid the use of `NonNull::cast`.

> How's that "escape hatch" supposed to work? I never really understood the point of the trait.

The premise is that we might, in a minor version of rust-secp, increase the **major** version of rust-secp-sys. Normally, because we're exposing rust-secp-sys types through rust-secp, this would be illegal according to semver. But if we're *only* exposing inner types through this obscure trait that we've explicitly documented as not being semver-compliant, we can get away with it.

To be clear, I don't mean to imply that we've achieved consensus on this and that we're going to do it...only that *I* think it's reasonable and I am intending to push on it.

The goal is that rust-secp could hit 1.0 before libsecp256k1 (and therefore secp-sys) does.

**Comment by Kixunil** [comment]
Where is it documented as unstable? I don't see it. Surprisingly, it's also in the sys crate rather than wrapper crate. Also I think it should be in an `unsatable` module so it's visible in the code, not just documentation.

I agree with the general idea, I just don't see the current implementation as sufficient.

**Comment by apoelstra** [comment]
Yes, sorry, to be clear, the current implementation is not sufficient (we have never released a major rev of secp-sys without a major rev of secp, and we'd have to fix this before we could).

>Also I think it should be in an unsatable module

oo, I like this idea.

**Comment by tcharding** [comment]
Are you mixing up "major" and "minor", we are on 0.x.y for both crates - major.minor.patch, right? Can't we release 1.x.y of secp and keep secp-sys on 0.a.b then we can always bump minor in secp when we do a minor bump in secp-sys (which horribly is a major release because we are pre-v1 ... holy f**k is semver compliance a lost cause?)
