### ISSUE TITLE
Replace types.rs with `core::ffi`

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#552]
Since 1.30 we've had this whole module https://doc.rust-lang.org/stable/core/ffi/index.html with all the ffi types we need. So no need for a libc dep and no need for our own slightly-wrong definitions.

**Comment by elichai** [comment]
Almost all the types in there are actually pretty new, since 1.64, we already use c_void from there which is old enough,
See c_char for example: https://doc.rust-lang.org/stable/core/ffi/type.c_char.html

**Comment by apoelstra** [comment]
Oh, I'm an idiot. I got all excited about `c_void`.
