### ISSUE TITLE
Implement From<KeyPair> for PublicKey

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#560]
Also for references, see also https://github.com/rust-bitcoin/rust-bitcoin/issues/1452

Should be good first issue.

**Comment by tcharding** [comment]
We have this already
```rust

impl From<KeyPair> for PublicKey {
    #[inline]
    fn from(pair: KeyPair) -> Self { PublicKey::from_keypair(&pair) }
}
```
https://github.com/rust-bitcoin/rust-secp256k1/blob/29c13638dc679db708fa466376650cb0bf758eff/src/key.rs#L1007

**Comment by Kixunil** [comment]
Oh, I checked tweaked version and then just trusted @casey didn't miss this one. Doc link: https://docs.rs/secp256k1/0.24.2/secp256k1/struct.PublicKey.html#impl-From%3C%26%27a%20KeyPair%3E-for-PublicKey
