### ISSUE TITLE
The current implementation of `bitcoin-hashes` alias is a significant footgun

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#562]
https://github.com/rust-bitcoin/rust-bitcoin/pull/1450#issuecomment-1341909410

The idiomatic (and expected!) way to activate features is by the crate name. Which is `bitcoin_hashes`. The `secp256k1` crate defines an alias, which is OK but then it itself MUST NOT use that alias. Otherwise the old name won't work and there's no easy way to tell for the users.

Alternatively there could be:

```rust
#[cfg(all(feature = "bitcoin_hashes", not(feature = "bitcoin-hashes")))]
compile_error!("Activate feature `bitcoin-hashes` instead of `bitcoin_hashes`");
```

But I don't see a good reason for forcing people to break the standard way of defining features.

**Comment by apoelstra** [comment]
I think we should just audit the code for usage of the alias. We should fix this before the release that we're about to push out.

I wouldn't mind removing it ... but if we never gate stuff on it, it should be harmless.

**Comment by tcharding** [comment]
I made this mess, I'll fix it.
