### ISSUE TITLE
Link to the repo in the docs

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#570]
@sipa points out that if you go to https://docs.rs/secp256k1/latest/secp256k1/index.html there is no way to find the github repo. We should add a link.

**Comment by sanket1729** [comment]
I take it that this is an issue for rust crates.

**Comment by apoelstra** [comment]
So, it turns out that in the header bar there is a dropdown you can click that will link you to the repo. So maybe this is not such a big deal. But I have also seen other crates that have a repo link in the docs, so I don't think it'd be *wrong* to include one.

**Comment by Kixunil** [comment]
Oh, I thought this is about attribution of the secp256k1 library and the link would point to the C lib repo. I use the dropdown feature all the time but if it's less known (especially outside Rust devs) I wouldn't mind adding the link. But then it should be changed in rustdoc to make it more discoverable.

**Comment by Kixunil** [comment]
I mildly remember that it took me a while to find that one as well. I think I went to crates.io each time or something.

**Comment by apoelstra** [comment]
I'm going to go ahead and close this. In the future we may want to revisit this issue across the rust-bitcoin community, but I think @sipa's confusion is addressed by the existing docs.rs top bar.
