### ISSUE TITLE
Public key from a shared secret?

### ISSUE THREAD

**Issue by cryptoquick** [rust-bitcoin/rust-secp256k1#584]
I'm trying to do this:

```rust
    let ss = SharedSecret::new(&pk.into_inner(), &sk);
    let pk = PublicKey::from_secret_key_global(&SecretKey::from_slice(&ss.secret_bytes())?);
```

Unfortunately, I get this error: `Error: malformed or out-of-range secret key`

Is there a better way to get a public key from an ECDH shared secret?

The scenario, for the curious, is to use the [ecies](https://docs.rs/ecies/latest/ecies/) crate to encrypt information shared between a client and a server, like a form of E2EE.

**Comment by Kixunil** [comment]
Is it possible for you to share the exact values? What you encountered should be cryptographically unreachable. IOW, it should be more probable that the Earth is destroyed than you encountering this error.

OT: we really should have `From<SharedSecret> for SecretKey`.

**Comment by apoelstra** [comment]
i"m really surprised that that ECIES crate would expose the internals of the cryptosystem enough that you'd need to care about the details of the shared secret. The `encrypt` function in its API, while weakly typed, does not seem to require this. There are other things about that crate that raise my eyebrows, such as the bizarre mixing of a hand-rolled Rust impl of secp256k1 with OpenSSL.

Furthermore, ECIES never requires that you obtain a public key from a shared secret.

**Comment by cryptoquick** [comment]
My apologies, I lost in my own code. I actually got this error because I was accidentally trying to use a public key as a secret key.

**Comment by apoelstra** [comment]
All good! I consider this to be a win for our deliberately constraining API :)
