### ISSUE TITLE
Improving slow pubkey generation.

### ISSUE THREAD

**Issue by hsnamed** [rust-bitcoin/rust-secp256k1#586]
Is it ok that creation of PublicKey from SecretKey took 49 keys per ms ?
- Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
- rustc 1.66.0
- opt-level=3
- secp256k = 0.26

Did i missed some optimization points ?

**Comment by apoelstra** [comment]
20 microseconds per key sounds pretty fast actually. I would expect it to take 50%+ longer than that actually.

Why do you think this is slow?

**Comment by Kixunil** [comment]
Obligatory: did you compile with `--release`?

**Comment by hsnamed** [comment]
Its just assumption, ive tried recompile secp256k1 c implementation --with-ecmult-window=24 instead default 15, it makes more  precomputed generation points , but it doesnt improve calculation performance , still the same 50 keys per ms.

**Comment by apoelstra** [comment]
Yeah, the default precomputation size pretty-much max out the potential performance gains. Increasing it might even worsen performance by having worse cache locality.

I'm going to close this since it looks like our perf is consistent with upstream.
