### ISSUE TITLE
Build failing on macOS using 1.41.1

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#589]
It looks like builds using MSRV [fail on macOS](https://github.com/Kixunil/bip21/actions/runs/4425685474/jobs/7761248599) but [succeed using stable](https://github.com/Kixunil/bip21/actions/runs/4425685474/jobs/7761248392). I'm not sure if this is even fixable and how to fix it. Given we will move to 1.48 and nobody complained yet (presumably macOS users tend to use rustup/newer compiler) I suggest to just ignore this. What do you think?

**Comment by apoelstra** [comment]
I think this is a known issue "you cannot use rust 1.41 on a Mac" but I can't find the reference now.

**Comment by Kixunil** [comment]
Not sure about "Rust" since this failed in `secp256k1` build. It could be `cc` bug though. I also mildly remember seeing this but don't remember where.

**Comment by Kixunil** [comment]
Oh, remembered, this looks similar: https://github.com/romanz/electrs/issues/858
