### ISSUE TITLE
The ECDH shared secret does not agree with that generated by NodeJS's computeSecret().

### ISSUE THREAD

**Issue by fadedbee** [rust-bitcoin/rust-secp256k1#634]
The full details are at: https://stackoverflow.com/questions/76755083/rust-ecdh-does-not-produce-the-same-shared-secret-as-nodejs-javascript-and-c-imp

Should I expect the ECDH shared secret for two keypairs to be the same as NodeJS's computeSecret() on secp256k1 keys?

**Comment by apoelstra** [comment]
It looks like Javascript is outputting the actual x-coordinate of the EC point. You may need this for compatibility with existing schemes but if you are doing your own shared secret implementation you definitely should not be using it directly. See the warning on https://docs.rs/secp256k1/latest/secp256k1/ecdh/fn.shared_secret_point.html
