### ISSUE TITLE
Get r,s,v 

### ISSUE THREAD

**Issue by ItsFunny** [rust-bitcoin/rust-secp256k1#651]
How can i get the r,s,v from the signature ?  like these:

let key = key.into();
let msg = Message::from_slice(claim_hash.as_slice())?;
let signature=key.sign_ecdsa(msg);

r?s?v?

**Comment by Kixunil** [comment]
Why would you need it? This library is not intended for people to write their own crypto. But you can serialize it and read the values from serialized representation. Just note that only r and s are serialized.
