### ISSUE TITLE
from_slice throwing InvalidPublicKey when PK is actually valid

### ISSUE THREAD

**Issue by gbenattar** [rust-bitcoin/rust-secp256k1#67]
Consider the following PK (serialized as a point having hex bigInt):

```
x: '5f6853305467a385b56a5d87f382abb52d10835a365ec265ce510e04b3c3366f'
y: 'b868891567ca1ee8c44706c0dc190dd7779fe6f9b92ced909ad870800451e3'
```

y has a length of `248 (31)`  but from_slice expect` 1 + 32 (x) + 32 (y)` and return for such input `InvalidPublicKey`. As a workaround we created a wrapper which pad coordinate(s) to make it 32 (https://github.com/KZen-networks/cryptography-utils/commit/3e2a710c9b5015926553ecebfd704907d29050fe#diff-99ffb7b09882f90f6bf48a2d6247c2dcR267).

Shouldn't this big taken care within from_slice?
The error give the perception that x, y does not form a valid public key.

Let us know,

**Comment by apoelstra** [comment]
No, `from_slice` only takes valid public keys, and if a coordinate is encoded in 31 bytes that is not a valid public key.

**Comment by apoelstra** [comment]
In libsecp a public key is not an abstract pair of field elements. It is a byte string specifically encoded as per section 2.3.3 of http://www.secg.org/sec1-v2.pdf
