### ISSUE TITLE
The full documentation link in readme.md is broken.

### ISSUE THREAD

**Issue by arik-so** [rust-bitcoin/rust-secp256k1#68]
As such, this library does not appear to have any documentation. Some examples might prove really helpful. Thanks!

**Comment by apoelstra** [comment]
Maybe fixed by https://github.com/rust-bitcoin/rust-secp256k1/pull/66

**Comment by TheBlueMatt** [comment]
For the time being, you can still read the docs for old versions on docs.rs.

**Comment by apoelstra** [comment]
You can also build the docs locally using `cargo doc`. They will appear under `target/doc/secp256k1/index.html` I think.

**Comment by apoelstra** [comment]
Fixed in #66
