### ISSUE TITLE
Schnorr - bitcoin - combine 2 schnorr signatures

### ISSUE THREAD

**Issue by tinguyen1107** [rust-bitcoin/rust-secp256k1#694]
Hi guys, I'm trying to implement the statecoin protocol, I used the schnorr to handle the multisig between the server and user. We create the signature using this one

    let sighash = sighasher
        .taproot_key_spend_signature_hash(input_index, &prevouts, sighash_type)
        .expect("failed to construct sighash");

    let tweaked: TweakedKeypair = keypair.tap_tweak(&secp, None);
    let msg = Message::from(sighash);

    let signature = secp.sign_schnorr(&msg, &tweaked.to_inner());

    let signature = bitcoin::taproot::Signature {
        sig: signature,
        hash_ty: sighash_type,
    };
I wonder that how we can combine 2 sign together and spend the transaction?

**Comment by apoelstra** [comment]
dupe of https://github.com/rust-bitcoin/rust-secp256k1/issues/694
