### ISSUE TITLE
`SecretKey::new()` and `KeyPair::new()` can be implemented without loops

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [rust-bitcoin/rust-secp256k1#698]
We can generate 256 bit number in range `[1; N)`, where `N = FFFFFFFF_FFFFFFFF_FFFFFFFF_FFFFFFFE_BAAEDCE6_AF48A03B_BFD25E8C_D0364141`. 
https://github.com/rust-bitcoin/rust-secp256k1/blob/6648126c69ce8056d053cbaa22246d12c76f3fc1/src/key.rs#L190-L204

**Comment by apoelstra** [comment]
What are you talking about?

**Comment by StackOverflowExcept1on** [comment]
@apoelstra I'm saying that `crate::random_32_bytes(rng)` and loops can be replaced by generating number within given range for an elliptic curve secp256k1.
