### ISSUE TITLE
Deprecate `Message::from_digest_slice`?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-secp256k1#710]
There is `from_digest` method which is more straightforward for probably all use cases - any serious hash engine will output an array, not a slice/vec/whatever. And in the rare scenarios where people use hash engines with crappy API they can just call `.try_into().unwrap()` themselves - no need to pollute our API.

**Comment by apoelstra** [comment]
Yeah, not a bad idea. Especially since we expect people to mostly stop using `Message` conversions anyway.
