### ISSUE TITLE
ElligatorSwift "A/B" enum should have better-named variants

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#741]
I think we can create a new enum, deprecate the old one, and use `Into` generics to make this a non-breaking change for most users.

**Comment by Kixunil** [comment]
Good idea, especially if you mean `Into<NewEnum>`.

**Comment by Davidson-Souza** [comment]
As the one to blame for this unfortunate naming, I agree that it should be clearer. The comments use "Initiator" and "Responder'. If you consider this is used in during a connection handshake, I think those makes sense.

**Comment by liamaharon** [comment]
Any suggestions for a more creative name for the new enum than `ElligatorSwiftPartyV2`?

**Comment by apoelstra** [comment]
I think we could shorten it to `Party` since it's in the `ellswift` module, the term "party" isn't used anywhere else, and with the long variant names it'll be better to have a short enum name.
