### ISSUE TITLE
secp256k1-sys v0.10.1 released as a crate but not available here?

### ISSUE THREAD

**Issue by shesek** [rust-bitcoin/rust-secp256k1#742]
The v0.10.1 crate was released yesterday: https://crates.io/crates/secp256k1-sys/0.10.1

However the latest version on current master is v0.10.0:

https://github.com/rust-bitcoin/rust-secp256k1/blob/d042094a90f92c944dfc28332ebc140dbd4ef285/secp256k1-sys/Cargo.toml#L3

**Comment by Kixunil** [comment]
It's in the 0.29.x branch.

**Comment by shesek** [comment]
Ah I see, my apologies  for the confusion :)
