### ISSUE TITLE
Global context is randomized twice

### ISSUE THREAD

**Issue by DaniPopes** [rust-bitcoin/rust-secp256k1#759]
In:
https://github.com/rust-bitcoin/rust-secp256k1/blob/bb4972f20fb5a1681a103ffd4d3c27cf31679278/src/context.rs#L44-L63

`Secp256k1::new` itself calls `randomize` with rand: https://github.com/rust-bitcoin/rust-secp256k1/blob/bb4972f20fb5a1681a103ffd4d3c27cf31679278/src/context.rs#L206-L234

Is this intended? If not, the call in `deref` should be dropped.

**Comment by apoelstra** [comment]
Good catch. Yeah, let's drop the one in `deref`.

cc #388
