### ISSUE TITLE
Calling `Secp256k1::randomize` on a verification-only context will abort the process

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#82]
TIL that `secp256k1_context_randomize` actually requires a signing context, despite the docs not mentioning this. See https://github.com/bitcoin-core/secp256k1/issues/573

The following code can trigger a process abort in a unit test (run with `cargo test --features "rand"`)
```
diff --git a/src/lib.rs b/src/lib.rs
index 81cbc57..2b0a4a7 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1179,6 +1179,13 @@ mod tests {
 
         assert_tokens(&sig, &[Token::BorrowedBytes(&SIG_BYTES[..])]);
     }
+
+    #[cfg(feature="rand")]
+    #[test]
+    fn test_randomize() {
+        let mut s = Secp256k1::verification_only();
+        s.randomize(&mut ::rand::thread_rng());
+    }
 }

 #[cfg(all(test, feature = "unstable"))] 
```

**Comment by apoelstra** [comment]
As a secondary bug, there are no unit tests for the context randomization function.

**Comment by real-or-random** [comment]
This has been fixed upstream.

> As a secondary bug, there are no unit tests for the context randomization function.
> 
> **Edit:** Ah, there sorta are, but they're spread throughout the rest of the tests and I evidently only thought to add it to signing tests.
Closing here for now but just reply if you think that we should improve that.

**Comment by apoelstra** [comment]
I guess we ought to reopen until we update our C code to use the new upstream.
