### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by MathieuDutSik** [rust-bitcoin/rust-secp256k1#97]
I am trying to use the `rust-secp256k1` and I have problem with compiling the examples. I would much appreciate is a *main.rs* file were in the git repo.

Two problems I encounter:
* In order to use the library with key generator, one needs to write
```
secp256k1 = { git = "https://github.com/rust-bitcoin/rust-secp256k1", features = ["rand"]}
```
It would be helpful to have this written explicitly.
* In the code (with rustc version 1.32.0 and rand 0.6.5) one needs to change **use rand::OsRng;** to **use rand::rngs::OsRng**
* After those changes, one is left with the following error
```
error[E0277]: the trait bound `rand::rngs::OsRng: secp256k1::rand::Rng` is not satisfied
  --> src/main.rs:12:41
   |
12 |     let (secret_key, public_key) = secp.generate_keypair(&mut rng);
   |                                         ^^^^^^^^^^^^^^^^ the trait `secp256k1::rand::Rng` is not implemented for `rand::rngs::OsRng`
```
which I do not know how to resolve.
Thank you in advance for any help in resolving those problems.

**Comment by apoelstra** [comment]
You need to use the correct version of the `rand` crate. The easiest way is to just use the re-exported one at `secp256k1::rand`.

**Comment by MathieuDutSik** [comment]
Thank you. I could implement it. I think the manual and example could easily be better.

See in attachment the file that follows your advice
[test_secp256k1.zip](https://github.com/rust-bitcoin/rust-secp256k1/files/2836041/test_secp256k1.zip)

If you choose so, you could insert it or something similar in an example directory.

  Mathieu

**Comment by real-or-random** [comment]
Yes, good point, we should improve the documentation. But I don't think that we want an example directory; an updated example in the docs should be enough.

@MathieuDutSik Now that you have working example code, do you want to give it try and submit a pull request? If not, is it okay that we include your example code in the documentation?

**Comment by real-or-random** [comment]
@MathieuDutSik Can we use your example code in the documentation?

**Comment by apoelstra** [comment]
I'd like an examples directory actually
