### ISSUE TITLE
Incompatibility with ring when compiling to Android

### ISSUE THREAD

**Issue by maciejhirsz** [rust-bitcoin/rust-secp256k1#98]
#85 pinned `cc` to `1.0.26` which makes Android builds using latest NDK (`r19` at the time of this writing) and depending on ring `0.14.6` fail to compile.

My current workaround is to downgrade `Cargo.lock` to use `secp256k1 0.12.0` which doesn't pin the `cc` version, and upgrade `cc` back to `1.0.29`.

I'd like to know what was the rationale of the author of #85 behind adding the pin, but I'm kind of afraid to ask given the _intensity_ of that PR :sweat_smile:.

**Comment by maciejhirsz** [comment]
Yeah, I've been running into so many spooky issues in my particular case (and I haven't tried compiling to iOS) I've started switching all dependencies to use the pure-Rust `libsecp256k1` (which is a shame, as there is so much stuff built on top of your crate!).

Just to give you some flavor, last issue I had: Android release built fine, normal `cargo build` x86_64 binary built fine (both debug and release), but `cargo test` failed to compile :sweat_smile:.

Anyway, I reckon my issue is so exotic I can probably close this.

Side note: I've been reading through some other crates in `rust-bitcoin`, this is some of the cleanest code I've seen!

**Comment by apoelstra** [comment]
Thanks for your kind words :) the credit goes to @dongcarl and @stevenroose for the clean code.

I think if it's only `cargo test` that's failing, this is OK, since downstream users won't run that on our library?

**Comment by maciejhirsz** [comment]
Yeah, but I do want to be able to run the tests :upside_down_face:.
